### ISSUE TITLE
Taxonomy node square expander thingies display incorrectly

### ISSUE THREAD

**Issue by jpsullivan65** [NaturalHistoryMuseum/scratchpads2#6526] opened 2022-02-10 21:53 UTC
**Describe the bug**
The little squares with the "+" sign in the middle to expand the taxonomy do not display correctly UNTIL you click on a name and the screen refreshes and then they do.  

**To Reproduce**
see https://mormyrids.myspecies.info/en/taxonomy/term/430
**Screenshots**
See 2 screenshots.  One showing issue, other after refresh.
**Your setup:**
 - Scratchpad URL: see above.
 - Browser: Chrome, Safari

**Impact**
Significantly impacts user experience.

**Anything else?**
<img width="910" alt="Screen Shot 2022-02-10 at 4 14 26 PM" src="https://user-images.githubusercontent.com/21112349/153502685-38f5ab8b-d6a4-44fb-a468-da06bbc472ff.png">
<img width="756" alt="Screen Shot 2022-02-10 at 4 15 40 PM" src="https://user-images.githubusercontent.com/21112349/153502764-80c172d7-0124-4017-96c2-aa8107f8a6d2.png">

**Comment by jpsullivan65** [comment] 2022-02-10 21:54
Note: Exact problem has occurred before (1+ year ago?) and was fixed.

**Comment by therobyouknow** [comment] 2022-03-04 11:38
Thank you for advising - this is definitely a bug, which doesn't seem to have been properly fixed and therefore needs to be fixed.

The root cause of this is that the initial page display uses "www" in the web address for the plus and minus images.

This results in the call to address https://www.mormyrids.myspecies.info/sites/all/modules/custom/tinytax/images/minus.gif being attempted, which does not work.

The correct address is https://mormyrids.myspecies.info/sites/all/modules/custom/tinytax/images/minus.gif without the www.

www.mormyrids.myspecies.info is not the valid address, mormyrids.myspecies.info is the valid address.

The above confirmed with analysis below.


![image](https://user-images.githubusercontent.com/1080646/156755831-0afd9509-88b3-4e12-b8c5-71f19601cee1.png)

![image](https://user-images.githubusercontent.com/1080646/156756008-4f37c400-a2dd-47f2-b2a9-5a17adc6c535.png)

The fix will be to trace the scratchpads software code that inserts www into the URL and then remove it.

Thank you very much for providing the steps - I was able to use them to see the problem to then analyse.

**Comment by therobyouknow** [comment] 2022-03-07 10:10
above is something I'll also need to look into fixing. I've seen this before on scratchpads sites.

**Comment by jpsullivan65** [comment] 2022-03-07 18:15
I was just about to post the above observation re what you posted just above.  Noticed this last night. Re the first problem, why/how was this problem fixed for months and has just now come back and why aren't all Scratchpads affected?

**Comment by jpsullivan65** [comment] 2022-03-11 14:19
Any estimate on when I can get my Scratchpad back in working condition?  I actually need it to function.  It hasn't been for most of 2022 so far.

**Comment by therobyouknow** [comment] 2022-03-12 00:53
Thank you John for advising about the ongoing problems you are experiencing.

Obviously I am familiar with these ongoing issues and my apologies that they are continuing. I am committed to resolving them and will be resuming working on these performance issues, in this month of March, as I had mentioned here:
https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6515#issuecomment-1028903040
and onwards.

As that above comment says I also mentioned February as well as March to work on this as well, so I'm adrift on working on the improvements as we're now into March. To outline some items related to scheduling:  I meeded to allocate some time over the past several weeks to another project in NHM, but there is a deliverable for that project during week commencing 14 March, after which I'll be looking forward to giving Scratchpads some more time. I am also taking 5 days holiday/vacation toward the end of March to catch up on some home improvements and personal admin. I will arrange with my colleagues toassist with communicating on issues during that time. And in general, I'd expect our work to run from March into April at the moment, in terms of working on improvements and beyond as well.

With some scheduling matters touched upon above, then, going back to the technical matters to solve the performance issues: as had been mentioned we already have an additional server that we have yet to utilise which will be part of the above work. On or a little after 16 March I'll discuss with my colleagues how to utilise this in the best way as well as the other improvements.

Other items will be addressed including the email communication and things like the missing images and styling on some pages: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6526

Thanks again for getting in touch. The issues you are encountering are clearly frustrating. I like to check respond to the issues, but share the frustration, as I don't just want to acknowledge the issues and outline solutions but also actually implement them for you at a predictable and consistent pace and that is what I endeavour to improve upon.

Rob

**Comment by jpsullivan65** [comment] 2022-03-14 03:35
Thanks, Rob.  I know you're stretched.

**Comment by jpsullivan65** [comment] 2022-03-14 03:37
My Scratchpad is currently back in business, with the classification page working again.

**Comment by therobyouknow** [comment] 2022-03-16 14:44
Good to hear thank you very much John but I note from Facebook there are some further issues since then. My above previous post would still apply to fixing them long term.

**Comment by jpsullivan65** [comment] 2022-03-20 20:02
Rob, unless you did something to resolve the original issue raised here, I may have resolved it by clearing the cache for my site (https://mormyrids.myspecies.info/en/taxonomy/term/430#overlay=en/admin/config/development/clearcache).  The node squares on the classification are now displaying correctly.

**Closed** 2022-07-14 12:23 UTC
Labels: type: bug, status: triage
