### ISSUE TITLE
Reduction of spam accounts

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6271] opened 2020-09-15 09:12 UTC
Most spam accounts fill mandatory fields "Other/given name(s)" and "Family name" with two-digit numbers, like 85, 37, etc. Please, create a rule banning numeric characters in those fields. That way we will get rid of most spam accounts and emails and save ourselves some work. Thank you in advance!

**Comment by alycejenni** [comment] 2020-12-07 17:44
duplicate of #5520

**Closed by alycejenni** 2020-12-07 17:44 UTC
Labels: spam registrations, type: feature
