### ISSUE TITLE
Page not being indexed by Google

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5738] opened 2018-12-23 14:13 UTC
- Added by [George Beccaloni](http://wallacefund.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Website](http://wallacefund.info)

### Description:

I am concerned that my Wallace Website is no longer appearing in Google Search results. I discovered that it isn’t now indexed by Google because of “Server error (5xx)”. Are you aware of this problem (which is a serious one for me) and if so, whether you are planning to fix it? Thanks.

**Comment by jrdh** [comment] 2018-12-28 14:19
Duplicate of https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5740 but for a different site. Also seems to be fine.

**Closed by jrdh** 2018-12-28 14:19 UTC
