### ISSUE TITLE
Scratchpad not working.  

### ISSUE THREAD

**Issue by jpsullivan65** [NaturalHistoryMuseum/scratchpads2#6606] opened 2022-11-21 14:13 UTC
Taxonomy pages not loading:
 e.g.
https://mormyrids.myspecies.info/en/taxonomy/term/430

**Comment by therobyouknow** [comment] 2022-11-21 14:43
Thanks @jpsullivan65 I noticed this too. Will enquire with our infrastructure team.

**Comment by therobyouknow** [comment] 2022-11-21 14:46
Some sites are now coming back online from my checking, but slowly could you try now @jpsullivan65 please?

**Comment by therobyouknow** [comment] 2022-11-21 15:03
I've messaged our infrastructure team, as it looks like your site is unresponsive again.

**Comment by jpsullivan65** [comment] 2022-11-21 15:45
Unfortunate timing.  As a result of a new publication a lot of new people are following links to the site.  :(

~ John

**Comment by therobyouknow** [comment] 2022-11-22 12:39
This looks better today from what I can see, @jpsullivan65 John.  Can you advise how it looks for you on your side?

https://mormyrids.myspecies.info/en/taxonomy/term/430

Cause of issue from our infrastructure team:
"authentication issue..." "...causing ssh slowness."

**Comment by jpsullivan65** [comment] 2022-11-22 13:10
Looking good this morning as far as I can tell.  Thanks!  ~ J

**Comment by therobyouknow** [comment] 2022-11-29 07:58
Closing issue as root cause identified and resolved.

**Closed by therobyouknow** 2022-11-29 07:58 UTC
Labels: type: bug, status: triage
