### ISSUE TITLE
Can no longer include italic tags in biblio titles

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6039] opened 2019-10-14 15:05 UTC
![Screenshot 2019-10-14 at 16 04 42](https://user-images.githubusercontent.com/929684/66761702-6c40b680-ee9c-11e9-84d4-edd28028c1e8.png)

**Comment by PaulKiddle** [comment] 2019-10-14 16:15
Duplicate of #5982

**Closed by PaulKiddle** 2019-10-14 16:15 UTC
