### ISSUE TITLE
Search on front page #6263

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6362] opened 2021-06-02 11:32 UTC
- Added by [Paul Cannon](http://fungi.myspecies.info/user/2)
- Scratchpad: [Fungi of Great Britain and Ireland](http://fungi.myspecies.info)

### Description:

Not sure if there has been any progress on this? Could be a quite simple fix...
Best wishes
Paul

**Comment by alycejenni** [comment] 2021-06-02 13:39
duplicate of #6263
(there hasn't been any progress on it, but when there is it'll be posted under the original issue!)

**Closed by alycejenni** 2021-06-02 13:39 UTC
Labels: status: duplicate
