### ISSUE TITLE
Access denied for taxonomy page

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6055] opened 2019-10-28 01:14 UTC
- Added by [Marco Gaiani](http://neotropicalcicadellidae.myspecies.info/user/2)
- Scratchpad: [Neotropical Leafhoppers](http://neotropicalcicadellidae.myspecies.info)

### Description:

Again my taxonomy page is unavailable. Any ideas on how to solve this more permanently? It can't be that any new additions via file update will break the access to the page

**Comment by benscott** [comment] 2019-12-19 11:50
Duplicate of #5989 - this is now fixed.

**Closed by benscott** 2019-12-19 11:50 UTC
