### ISSUE TITLE
Blocked from viewing image

### ISSUE THREAD

**Issue by BarryWarrington** [NaturalHistoryMuseum/scratchpads2#6457] opened 2021-11-20 21:46 UTC
When I click on a photo on a particular species page, the image doesn’t load up. When I try to download the image, the attached error message comes up.

Could it be that the species in question is called Liriomyza cannabis?

Please can this be looked at?

Many thanks,

Barry.

![A8069262-D15E-484A-9299-80E810FF25ED](https://user-images.githubusercontent.com/75427252/142741744-a93e9c07-cc43-4534-8744-8242a8f789c4.png)

**Comment by therobyouknow** [comment] 2021-11-22 11:27
Thank you for altering Barry. Confirming I also see this issue at https://agromyzidae.myspecies.info

As you say it might appear that the Firewall has some rules on content filtering. The next step would be for me to liaise with our infrastructure team to get precise definitions of what this actually is.

top: https://agromyzidae.myspecies.info/gallery?f%5B0%5D=im_field_taxonomic_name%3A240
(where you see the issue)

bottom: https://agromyzidae.myspecies.info/gallery?f%5B0%5D=im_field_taxonomic_name%3A238
(another page where the issue not seen)

![image](https://user-images.githubusercontent.com/1080646/142852450-265e8ffb-a694-4ee0-999f-a0207e1d8498.png)

**Comment by therobyouknow** [comment] 2021-12-06 13:48
Issue raised today with our infrastructure team in TS with regard reviewing possible firewall content filtering rules.

**Comment by therobyouknow** [comment] 2021-12-07 18:45
looks like following now ok:
https://agromyzidae.myspecies.info/gallery?f%5B0%5D=im_field_taxonomic_name%3A240

screenshot:
![image](https://user-images.githubusercontent.com/1080646/145087449-48a277cc-fa81-460a-8d5b-01318ab19b66.png)


Our infrastructure team advise:

> Our Platforms Manager seems to have found the culprit.
> The images in question were actually being blocked because they had a tilde in the URL which was triggering a "Forceful Browsing" block on the WAF.
> 
> This has been remediated for the domain in question so images *should* be accessible now. Can I ask you to confirm this for me please?
> 
> Thank you,

I will get back to them to advise the image is now showing. However, I have 2 queries myself:

1  - where was the 'tilde' i.e `~`  in the url? @BarryWarrington do you know what they mean by that ?
2 - site styling/formatting not showing on https://agromyzidae.myspecies.info/file-colorboxed/438 is that expected? if not, then I'll raise another ticket for me to look at.

**Comment by BarryWarrington** [comment] 2021-12-07 18:52
Thanks Rob, the images now load absolutely fine (for this species and the one I emailed about yesterday [Phytomyza gymnostoma]). 

I have absolutely no idea about the two queries I’m afraid.

Thanks again for getting the issues resolved.

**Comment by therobyouknow** [comment] 2021-12-08 11:28
Thank you Barry for advising.

Following only for information as to what the root cause was and outline of how it was fixed, in case needed for future. Also handy for me and other devs as a central point of reference for troubleshooting future issues.

(No action needed.)

Credit to Lewis and colleagues in our infrastructure and platform  (TS).

Closing ticket as issue resolved. Thanks again.

> Morning Rob,
> 
> Great to hear that it's working!
> 
> Yes, of course. This is an example of a problematic URL:
> https://agromyzidae.myspecies.info/sites/agromyzidae.myspecies.info/files/JV19803~03.jpg
> 
> Note the "~" in the name of the image. This is considered a non-standard URL character by Barracuda so was throwing the WAF.
> This would've affected the thumbnail images as they call the URL back which would've been blocked at the highest level, thus wouldn't have appeared as a thumbnail.
> 
> By sheer coincidence (apparently), the URLs which contained the tilde were also images of Cannabis genus plants. This originally got us thinking that it was a category block, but no such block exists, hence us looking elsewhere and finding the tilde exception.
> 
> You shouldn't have to change any naming processes you currently have as the entire domain has been allowed for tildes in the URLs. But this may occur again if different non-standard characters are used in future. Just to let you know!
> 
> Hope this helps and thanks for getting back to me,
> Kind regards,
>

**Closed by therobyouknow** 2021-12-08 11:28 UTC
Labels: type: bug, status: triage
