### ISSUE TITLE
Species pages not displaying

### ISSUE THREAD

**Issue by jpsullivan65** [NaturalHistoryMuseum/scratchpads2#6602] opened 2022-11-13 22:05 UTC
Species pages are not displaying correctly.  E.g. https://mormyrids.myspecies.info/en/taxonomy/term/368

![Screen Shot 2022-11-13 at 5 03 04 PM](https://user-images.githubusercontent.com/21112349/201546803-68c7833e-d7e4-402b-8daa-cf2abf339b66.jpg)

**Comment by therobyouknow** [comment] 2022-11-14 09:35
Possible duplicate of: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6519

**Comment by therobyouknow** [comment] 2022-11-14 09:58
**Summary**

Confirming duplicate of https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6519

Therefore, closing this ticket as a duplicate.  But that doesn't mean I'm not working on it!  I will continue the work in [that ticket](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6519) as I have done, don't worry!


**Technical analysis detail leading to confirming duplicate**

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1080646/201626142-3cb16193-6947-4304-bb88-948f5f81bdfe.png">

Inspected page and searched for `stylesheet` and observed that `www` referenced. Which is the [same issue] seen in the other ticket (https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6519#issuecomment-1223730508).

What is happening here is that the website is being visited with `www` in the URL.  `www` in the URL, as in `www.mormyrids.myspecies.info` is a not valid URL and therefore will not correctly load the site and its styling.

`mormyrids.myspecies.info` is the valid URL.

**Closed by therobyouknow** 2022-11-14 09:58 UTC
Labels: type: bug, status: triage
