### ISSUE TITLE
Problems with first access to my scratchpad

### ISSUE THREAD

**Issue by DavideDalPos** [NaturalHistoryMuseum/scratchpads2#6465] opened 2021-11-24 16:51 UTC
My scratchpad ( http://ichneumoninae.myspecies.info ) has been created but while clicking on the temporary link for login (for the first time), it gave me an error and I couldn't create a password. Right now I am stuck since even though I ask for a new password, I do not receive anything in my email. 

Is there a way I can resolve the Issue? 

Thanks,
Davide

**Comment by therobyouknow** [comment] 2021-11-26 09:42
Hello @DavideDalPos sorry about this issue. I agree this needs fixing.

To help me with my diagnostics, can you advise me what the error message was? What did it say? screenshots or pasted text fine :)  Thank you.

**Comment by DavideDalPos** [comment] 2021-11-26 21:09
Hello @therobyouknow,

Thanks for your fast response. So, when I click on the temporary link sent to me, I got the message in Figure 1 (which is normal since the link expired), but then, when I try to complete all the sections to get a new password, I receive the message in Figure 2. However,  I do not receive any email in my Inbox. 

I have tried three times already :-) 

I am sorry for this mess. :-) 

Davide
![Fig  1](https://user-images.githubusercontent.com/93291485/143650291-43b982d0-ac46-40e4-8feb-0bf55a026e1e.PNG)
![Fig  2](https://user-images.githubusercontent.com/93291485/143650337-514d147f-9a53-49e9-a58f-1c817c2d4ba6.PNG)

**Comment by Archilegt** [comment] 2021-11-28 13:05
@therobyouknow , @DavideDalPos needs to start working on his Scratchpad. Rather than waiting for a technological solution, please just create a password for him and send it directly to his email. Then Davide will be able to log in with his username and password, and create a new password.

**Comment by therobyouknow** [comment] 2021-11-29 09:29
I'll setup a login for you @DavideDalPos as @Archilegt suggests it looks like the quickest way to get you going again! Sorry about the issue here and thank you to both.

**Comment by therobyouknow** [comment] 2021-11-29 09:48
all done for you @DavideDalPos - email sent to the email address you used on the site.  I tested the login password and it works fine. Let me know how you get on.

Linking issue: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6447 for purposes of finding root cause.

**Comment by DavideDalPos** [comment] 2021-11-29 18:39
@therobyouknow It works perfectly!! :-) Thank you sir! :-) Amazing

**Comment by therobyouknow** [comment] 2021-12-07 16:23
thank you and you are most very welcome @DavideDalPos  Closing issue.

**Closed by therobyouknow** 2021-12-07 16:23 UTC
Labels: type: bug, status: triage

**Comment by therobyouknow** [comment] 2022-05-26 14:02
I'm pleased to advise that the password email facility should now be working, following initial testing. More detail here: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6447#issuecomment-1138610498
