### ISSUE TITLE
Large number of spam registrations

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6139] opened 2020-02-08 10:16 UTC
Coming from several sites. The first and last names always seem numeric so should be easy to block.

![Screenshot 2020-02-08 at 10 15 16](https://user-images.githubusercontent.com/929684/74083449-0df79f00-4a5c-11ea-8eb6-1b6584003561.png)

**Comment by alycejenni** [comment] 2020-12-07 17:44
duplicate of #5520

**Closed by alycejenni** 2020-12-07 17:44 UTC
Labels: spam registrations
