### ISSUE TITLE
Errors in DOI mapping

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6147] opened 2020-02-17 16:48 UTC
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

Hello team,
I am getting strange results while adding biblio references by using Pensoft's DOIs. I am getting the information for the parent article and the component figures aggregated in the title field, and I am getting the authors replicated as many times as total parts exist (e.g. 3 authors repeated six times). The XML files submitted by Pensoft to CrossRef seem complete but the publicly visible parent's JSON file in CrossRef shows no component_list and the components' JSON files show no reference to the parent's "container-title".
Example link for parent:
https://search.crossref.org/?q=10.3897%2Fsubtbiol.33.46444
and for one out of five components:
https://search.crossref.org/?q=10.3897%2Fsubtbiol.33.46444.figure1

In any case it would be worth checking if SP's internal DOI mapping calls the elements by using complete paths, e.g.:
//journal_article/contributors/name/given_name
//journal_article/contributors/name/surname

or shortened paths, e.g.:
//given_name
//surname
Short paths could be causing all sub-article elements' metadata to be harvested and aggregated into the parent article's metadata.

Cheers!

**Comment by jrdh** [comment] 2020-03-11 13:08
Having had a look at this, it seems that the issue is as you suspected - we're reading elements at any level regardless of their path and then mapping them over to the biblio entity. This could be fairly easy to fix assuming agreement on a correct mapping can be reached however it is worth noting that this code isn't Scratchpads specific, it's provided by the biblio drupal module. We're currently a few minor releases behind their drupal 7 latest release (we're on 7.x-1.0 whereas latest is [7.x-1.3](https://www.drupal.org/project/biblio/releases/7.x-1.3)) however from a cursory glance at the 7.x-1.3 source it also uses the same parsing methodology and would therefore have the same weaknesses.

We can of course patch this module to do what we want it to do but it would be a significant divergence. I also suspect we would find it difficult to map everything in a satisfactory way for all DOIs and it may be better to produce the result that you're seeing currently instead of missing some data during the import - but that needs investigation. @benscott / @PaulKiddle it'd be good to get your thoughts on this too if possible and whether there a case to say this is out of scope of the current development effort?

**Comment by alycejenni** [comment] 2021-06-02 10:42
[2.9.17.1](http://scratchpads.org/news/2021-05/scratchpads-release-2917) now released

**Closed by alycejenni** 2021-06-02 10:42 UTC
Labels: status: awaiting release, type: feature
