### ISSUE TITLE
Taxonomy tree page not accesible. Part 2

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5952] opened 2019-06-19 18:48 UTC
- Added by [Marco Gaiani](http://neotropicalcicadellidae.myspecies.info/user/2)
- Scratchpad: [Neotropical Leafhoppers](http://neotropicalcicadellidae.myspecies.info)

### Description:

Thanks for the great work! I was happy for about 27 min, But.... I just updated my taxonomy tree with an XLS file import and we are back to the same "Access denied" message. So perhaps the root of the problem is in the update as you suggested on your message

**Comment by jrdh** [comment] 2019-06-20 09:44
Presumed the same as https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5935, looking into this now.

**Comment by jrdh** [comment] 2019-06-20 09:52
Hi Marco, I've resolved this again in the same way as I did in the previous issue you raised. I'll close this but will have a look and see if I can work out what the root cause is. Don't hesitate to raise more issues if you have more problems when updating though!

**Closed by jrdh** 2019-06-20 09:52 UTC
Labels: bug
