### ISSUE TITLE
Map: region selection

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6198] opened 2020-04-15 12:17 UTC
- Added by [vblago](http://sciaroidea.info/user/9)
- Scratchpad: [Fungus Gnats Online](http://sciaroidea.info)

### Description:

La Reunion cannot be selected on distribution map

**Comment by alycejenni** [comment] 2020-04-20 09:35
duplicate of #6178 and #6187, fixed by #6188

**Closed by alycejenni** 2020-04-20 09:35 UTC
