### ISSUE TITLE
Map: region selection

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6187] opened 2020-04-03 13:35 UTC
- Added by [vblago](http://sciaroidea.info/user/9)
- Scratchpad: [Fungus Gnats Online](http://sciaroidea.info)

### Description:

Saint-Vincent cannot be selected as a region on map

**Comment by alycejenni** [comment] 2020-04-03 13:37
Duplicate of #6178

**Comment by scratchpads** [comment] 2020-04-03 13:37
Comment by [vblago](http://sciaroidea.info/user/9)

Sorry, Guadelupe, not Saint Vincent

**Closed by alycejenni** 2020-04-03 13:37 UTC
Labels: duplicate
