### ISSUE TITLE
Autofill not working in Biblio 

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#5933] opened 2019-05-21 10:08 UTC
Trying to use autofill for taxa in the taxonomic name box in Biblio

We get this message:

![error](https://user-images.githubusercontent.com/44700406/58087604-86b28480-7bc9-11e9-9dff-7eac65953b1b.jpg)

**Comment by jrdh** [comment] 2019-07-01 07:56
Apologies, thought I'd already flagged this up, but this is a dupe of https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5939

**Closed by jrdh** 2019-07-01 07:56 UTC
Labels: bug, needs investigating
