### ISSUE TITLE
edit function missing from pages [duplicate of #6501]

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6596] opened 2022-10-03 13:18 UTC
- Added by [Barry Warrington](https://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](https://agromyzidae.myspecies.info)

### Description:

The edit function is missing on a couple of pages on my website. On the 'Recording Agromyzidae' and 'Newsletter' pages, the edit tab has vanished whilst it is still present on all the others.

Please can this be looked at or let me know how to fix this.

Thanks.

**Comment by therobyouknow** [comment] 2022-10-04 12:17
**confirming can see issue and workaround**

Thank you Barry, confirming I can see your issue myself:

Recording Agromyzidae

https://agromyzidae.myspecies.info/node/3

![image](https://user-images.githubusercontent.com/1080646/193816545-da9488be-8b49-4993-892a-0edff4d40155.png)


and Newsletter

https://agromyzidae.myspecies.info/node/4

![image](https://user-images.githubusercontent.com/1080646/193816612-9fc88934-8fd4-409c-971b-269b075e7b83.png)


At the moment, I don't know why these have disappeared. No changes have been made that would cause this.

This will need investigation.


**workaround**

For the time being, the workaround  as perhaps you might know is to tack `edit` onto the end of the URLs to access editing:

Recording Agromyzidae
https://agromyzidae.myspecies.info/node/3/edit

Newsletter
https://agromyzidae.myspecies.info/node/4/edit

**Comment by BarryWarrington** [comment] 2022-10-04 14:53
Thanks Rob. I didn’t know about just adding edit on the end - that’s useful to know!

The issue is also present on this page;

![23495858-6397-4D76-A700-3E61CD78722B](https://user-images.githubusercontent.com/75427252/193852425-ce91b50d-65e0-4354-8a56-e3f2adb4a36d.png)

There may be other pages too I guess but I haven’t worked through them all (there’s a lot!).

**Comment by therobyouknow** [comment] 2022-10-05 08:32
Thank you Barry, noted about the other pages too.  

I can also see this issue on my own test site, on my Introduction tab.    

So it could be a scratchpads-wide issue - that can be useful to know to help me characterise the issue and a solution.

**Comment by Archilegt** [comment] 2022-10-06 07:06
Edit and Clone tabs also missing in this reference in Myriatrix:
https://myriatrix.myspecies.info/content/invasive-species-cylindrodesmus-hirsutus-pocock-diplopoda-polydesmida-haplodesmidae-spreads
It seems that there is a broader issue with broken tab associations across Content Types, paradoxically affecting just individual records. I am thinking of the Archilegt and Asombke profiles/biographies in Myriatrix, which are also affected by disassociated tabs while other biographies aren't.

**Comment by therobyouknow** [comment] 2022-11-15 11:19
Fix for this issue https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6501 could also fix this issue.

**Comment by therobyouknow** [comment] 2022-11-17 10:28
**dev notes, remaining items to complete ticket**

Checking Barry's site as I said I would.   Couldn't get hold of a copy of his site's db as access to live production not available due to some storage issues TS advised.  Expecting this to be resolved so will try now.

Once confirmed Barry's site OK I will regard this ticket as ready for release, with the code implementation for it. Making sure the original fix for something else that caused it still works; we want to keep the fix before but not have its side effects that caused this ticket.

**Comment by therobyouknow** [comment] 2022-11-17 13:53
Yes, as expected, confirming that fix will work for https://agromyzidae.myspecies.info/ following testing a copy of this site local personal dev setup, as screenshot shows:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/1080646/202463716-81c68390-ebac-44c2-b5c3-53816dc5511d.png">

**Comment by therobyouknow** [comment] 2022-11-17 14:17
Barry's database required this solution now documented and committed to sprint release branch, to enable the import to succeed:

https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/DDEV#problem-2

This potentially could happen with other sites as well.

**Comment by therobyouknow** [comment] 2022-11-17 15:03
Closing as duplicate of #6501 on the basis that the fix for #6501 also fixes this issue, as [confirmed in testing](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6596#issuecomment-1318672412).

However, regression testing of that fix for #6501 shows it needs to be refined because some unwanted tabs are now reshowing for non-biological items. What needs to happen is that Drupal system function tabs (View, Edit, Clone etc) need to show, while Scratchpad domain specific tabs are not shown for non-biological tabs.

**Closed by therobyouknow** 2022-11-17 15:03 UTC
Labels: status: duplicate
