### ISSUE TITLE
Thomas Najer publications

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5842] opened 2019-02-21 14:02 UTC
[Phthiraptera](http://phthiraptera.info)

- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

Author - Thomas Najer. There were three variations of this author. After merging Sratchpad, the name adopted by Scratchpad is TOMAS NAJER (9476). Another previous name that was used - Tomas Najer (8505). However, in CONFIGURATION _ BIBLIO SETTING, you will find that it stated he has 7 publication. If click into the name the listing of the 7 publications appeared. However, if one were to search his publications via LITERATURE (tag) Search, only THOMAS NAJER appears and when click on it, none of his publications are found. So not sure what happen here.

**Comment by benscott** [comment] 2019-10-03 12:38
Duplicate of #6024 - fixed by #6031.

**Closed by benscott** 2019-10-03 12:38 UTC
Labels: NHM project, bug, duplicate
