### ISSUE TITLE
Issues with large files

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6168] opened 2020-03-10 21:37 UTC
Uploading large files for the Recording content type regularly times out. This used to just be a problem offsite, but is now happening within the museum (tried on 2.15GB files which is a standard length for long field recordings). Can this be extended?

There are also issues with accessing files, the bitrate for downloads outside the NHM has slowed to around 3MB/s at best, it used to be much higher. I have also had issues when accessing files (of any size) for analysis - the transfers often start and then fail (using CURL) in progress. If they are then accessed later they often work. It seems to be some rather over-the-top rate limit? (I put this in Slack a while ago).

**Comment by jrdh** [comment] 2020-03-12 10:07
Closing as a dupe of https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6032.

**Closed by jrdh** 2020-03-12 10:07 UTC
