### ISSUE TITLE
Sitemap not visible

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5741] opened 2018-12-28 13:07 UTC
- Added by [George Beccaloni](http://wallacefund.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Website](http://wallacefund.info)

### Description:

I generated a Sitemap for my Scratchpad http://wallacefund.info but when I go to http://wallacefund.info/sitemap it says Access Denied! Why?

**Comment by jrdh** [comment] 2018-12-28 13:19
Dupe of https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5742

**Closed by jrdh** 2018-12-28 13:19 UTC
