### ISSUE TITLE
Biblio edits

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6244] opened 2020-07-08 08:55 UTC
- Added by [vblago](http://sciaroidea.info/user/9)
- Scratchpad: [Fungus Gnats Online](http://sciaroidea.info)

### Description:

Bibliographic details such as journal, volume, issue and pagination are being wiped if a file is being attached when a biblio record created. I have reported this issue several times, but nothing has been done, and no feedback received

**Comment by Archilegt** [comment] 2020-08-01 20:05
Yes, I have reported this myself. Not fixed yet and it is time consuming for large databases, because we need to add biblio in two steps instead of one.

**Comment by alycejenni** [comment] 2020-11-26 12:42
duplicate of #6127

**Closed by alycejenni** 2020-11-26 12:42 UTC
Labels: bug, duplicate
