### ISSUE TITLE
problems with photo's galery

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6240] opened 2020-06-11 13:55 UTC
- Added by [Maria Zabaleta](http://rocosos.myspecies.info/user/2)
- Scratchpad: [Puntas Rocosas del Uruguay](http://rocosos.myspecies.info)

### Description:

I'm sorry but my problem continues and I can't view the response because the chat rested too far in the issue's list. I send you de error's message twice.
I think that it's a problem with cron but I am not able to resolve it myself. Please help me. We are working with great amounts of information that needs to be indexed correctly.

**Comment by alycejenni** [comment] 2020-11-26 15:01
duplicate of #6226

**Closed by alycejenni** 2020-11-26 15:01 UTC
