### ISSUE TITLE
Error message when importing new locations

### ISSUE THREAD

**Issue by poospiza** [NaturalHistoryMuseum/scratchpads2#6006] opened 2019-09-03 12:21 UTC
Hi,
I get this error message when I run the import of Locations using the Excel template:

Unable to handle the provided embed string or URL.
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'field_map_latitude' cannot be null

**Comment by scratchpads** [comment] 2019-09-03 12:22
Comment by [N. M. Williams](http://ethoikos.myspecies.info/user/2)

http://ethoikos.myspecies.info/

**Comment by alycejenni** [comment] 2019-09-04 13:32
duplicate of #5995

**Closed by alycejenni** 2019-09-04 13:32 UTC
Labels: duplicate
