### ISSUE TITLE
Certificate errors at fungi.myspecies.info [duplicate of #6519]

### ISSUE THREAD

**Issue by Paul-Cannon** [NaturalHistoryMuseum/scratchpads2#6598] opened 2022-10-17 08:09 UTC
Hi there
One of our users has sent the following message, I think this is something you may be able to fix but I certainly can't! 
Any help would be appreciated...

Best wishes
Paul

Hello Paul

I think I've asked about this before but not had a reply.

Caz and I use your Fungi of Great Britain and Ireland website a lot.
Unfortunately we see a certificate error quite often, which we can work around, but is a pain.
Our Kaspersky anti-virus software complains about it, but other software may not.

It'll probably need your web host to sort this out.
So we'd be very grateful if you could ask them to have a look please.

In summary, the website certificate is *.myspecies.info
which matches [fungi.myspecies.info](https://ttps/fungi.myspecies.info/)
but does not match [www.fungi.myspecies.info](https://protect-eu.mimecast.com/s/5Qv7CJNR8HBrqB9sV67Im)
which is used in some web requests.

The solution will either be to update the certificate.
Or somehow to tell your Drupal NOT to use [www.fungi.myspecies.info](https://protect-eu.mimecast.com/s/5Qv7CJNR8HBrqB9sV67Im) - not exactly sure where, but I can try to help if needed.

Thanks in advance - it would be great for us if this were fixed.

Chris
01931 713240

The cached JavaScript and CSS files are at [www.fungi.myspecies.info](https://protect-eu.mimecast.com/s/5Qv7CJNR8HBrqB9sV67Im) which causes a certificate error, eg a network request here:

[https://www.fungi.myspecies.info/sites/fungi.myspecies.info/files/advagg_js/js__lV0W4-80xYkwkcFfZ4M9Mu95eR-tBXvSXT_6FGDOvi0__rEa8ghhJ1ZaQbJzzFKhtb2jDdi2ubW-cdBxUMNl9mPo__3wKn-QAtqjy3WhExZmqNVMBWwDHJp_fLhLBu3sFzoyo.js](https://protect-eu.mimecast.com/s/dyRUCKLR8tDE2D7HvsXw3)

**Comment by therobyouknow** [comment] 2022-10-17 08:18
Good morning @Paul-Cannon 

**solution known and being implemented and tested**

Thank you very much for your ticket and in particular the detail at the end of your comment with regard to the Javascript (JS) and CSS information: this informs me that our solution for another issue is expected to fix this. This other issue is: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6519

As regards timescale we will be aiming for releasing in approximately at the end of this month October or beginning of November.

**Comment by Paul-Cannon** [comment] 2022-10-17 08:25
Thank you very much - superb service!!!

**Comment by therobyouknow** [comment] 2022-11-09 11:02
I will be following up next week Monday 14 November as to when we are planning a release to fix this issue.

**Comment by therobyouknow** [comment] 2022-11-14 16:25
Closing this issue as duplicate of #6519. But that doesn't mean I've stopped working on it, just that the issue will be tracked in #6519 going forward.

**Closed by therobyouknow** 2022-11-14 16:25 UTC
