### ISSUE TITLE
Phthiraptera - Italics

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5896] opened 2019-03-19 14:50 UTC
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

Hi

Previously I could include functions like `<i>` and `</i>` to create italics for the title of the data record. e.g. if I wish to type Acaridodoidae to make it appear as italic I would type `<i>Acaridodoidae</i>`. However, in recent weeks if I carried out this action, Scratchpad would reject it and a warning note - invalid html would appear. Can you advise me how can I go about making alphabets italics? Thanks

**Comment by alycejenni** [comment] 2019-03-19 15:37
Unfortunately HTML in titles is broken at the moment - see #5872. I don't know of a  workaround at the moment, but if I find one I'll post it in the other issue.
Marking this as duplicate of #5872 and closing.

**Closed by alycejenni** 2019-03-19 15:37 UTC
Labels: NHM Project - Phthiraptera, duplicate
