### ISSUE TITLE
I cannot edit existing pages!

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5752] opened 2019-01-04 20:36 UTC
- Added by [George Beccaloni](http://wallacefund.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Website](http://wallacefund.info)

### Description:

When I try to do so the box which should display the existing text is blank!

**Comment by jrdh** [comment] 2019-01-07 10:34
Hi George, I expect this is due to the ongoing performance issues, I'll check once those problems are resolved.

**Comment by jrdh** [comment] 2019-01-09 10:40
Is this still an issue now that the sites are working better?

**Comment by benscott** [comment] 2019-01-29 09:08
Tested and page editing is functional again - closing this issue as it was most likely caused by the performance issue, but reopen if it's still a problem.

**Closed by benscott** 2019-01-29 09:08 UTC
Labels: bug
