### ISSUE TITLE
Cannot link file to biblio node

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6009] opened 2019-09-10 11:07 UTC
http://bio.acousti.ca/content/bioacoustic-monitoring-new-zealand-avifauna-and-after-aerial-1080-operations

http://bio.acousti.ca/sites/default/files/thesis_access_0.pdf

**Comment by edwbaker** [comment] 2019-09-10 12:57
In addition: 
http://bio.acousti.ca/content/variability-repertoires-and-singing-behavior-male-and-female-‘i‘iwi-drepanis-coccinea

http://bio.acousti.ca/sites/default/files/Beck_hilo.hawaii_1418O_10174.pdf

No warning or error messages in either case.

**Comment by alycejenni** [comment] 2019-09-10 14:08
Duplicate of #5994

**Closed by alycejenni** 2019-09-10 14:08 UTC
Labels: bug, duplicate
