### ISSUE TITLE
Referencing in glossary terms broken

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6014] opened 2019-09-13 15:14 UTC
Previously referencing using [bib]...[/bib] worked in glossary terms, it no longer does. Screenshot shows this not working for the term 'bioacoustician'. This was working 3-4 weeks ago if that helps locate the issue. 

![Screenshot 2019-09-13 at 16 11 18](https://user-images.githubusercontent.com/929684/64873588-4e83f580-d641-11e9-9906-d9009a226653.png)

**Comment by alycejenni** [comment] 2019-09-13 15:16
duplicate of #5997

**Closed by alycejenni** 2019-09-13 15:16 UTC
Labels: duplicate
