### ISSUE TITLE
Account deletion is painfully slow

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#6389] opened 2021-07-28 09:33 UTC
Account deletion is slow or times out, making it hard for maintainers to delete spam accounts.

Affected sites include:

- https://cate-araceae.myspecies.info/
- https://ubsc.myspecies.info/
- https://cate-araceae.myspecies.info/
- https://bionoset.myspecies.info/

**Comment by benscott** [comment] 2021-08-19 11:50
This was caused by the firewall performance issues and is now fixed.

**Closed by benscott** 2021-08-19 11:50 UTC
Labels: type: bug, status: triage
