### ISSUE TITLE
[DUPLICATE of #6550] Restore code and settings for autotagging 

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6572] opened 2022-07-15 16:44 UTC
New issue spawned off https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6400#issuecomment-984582351 for [Archilegt](https://github.com/Archilegt):

> Also, please check with @benscott what was the code and settings for the autotagging that the terms in the glossaries were meant to enable. That seemed not to be working. Example: If I have the term "antenna" in the glossary and enable an autotagging setting, the word "antenna" should be recognized anywhere else in Myriatrix text, and autotagged with a link to the glossary term. It is a very important feature and it would be very nice to have it back. :)

[Archilegt](https://github.com/Archilegt) please advise if this is still an issue - is it available to you now and working?

**Describe the bug**

**To Reproduce**
Tell us what you were doing when you found the bug, or (even better) tell us the steps to recreate it ourselves.

**Screenshots**

**Your setup:**
 - Scratchpad URL: 
 - Browser:

**Impact**
Is this a minor inconvenience, or is it making it completely impossible to work on your Scratchpad?

**Anything else?**

**Comment by Archilegt** [comment] 2022-07-15 17:19
Duplicate of #6550

**Closed** 2022-07-20 14:27 UTC
Labels: type: bug, status: duplicate, status: triage
