### ISSUE TITLE
Large uploads fail on Bioacoustica

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5763] opened 2019-01-11 14:19 UTC
Large file uploads are regularly failing, these were working fine before Christmas. Any ideas?

**Comment by jrdh** [comment] 2019-01-14 15:16
Once the AJAX bug fix has been released to Bioacoustica we can check to see if the problem is still present.

**Comment by edwbaker** [comment] 2019-01-20 13:48
This is still happening frequently:

An AJAX HTTP request terminated abnormally.
Debugging information follows.
Path: /file/ajax/field_recording/und/0/form-HnIzbOFSHBQJtDasUC6TnxbjK7C5wRDvKe1Sdf_aEeI
StatusText: n/a
ResponseText: 
Technical difficulties
Site is experiencing technical difficulties.  Please try again later.

ReadyState: ,

**Comment by edwbaker** [comment] 2019-01-23 16:56
I have checked that the other AJAX issues are fixed, which they are. This seems to be a new bug.

**Comment by benscott** [comment] 2019-02-18 16:16
This is possibly related to the server issues we were having - I've tried uploading images (jpg & tif, 100MB+) to your site and staging without error.  Was it a particular image / file size that was failing?

**Comment by edwbaker** [comment] 2019-02-19 14:47
Yes - seems to be OK now.

Thanks!

On 18 Feb 2019, at 16:16, Ben Scott <notifications@github.com<mailto:notifications@github.com>> wrote:


This is possibly related to the server issues we were having - I've tried uploading images (jpg & tif, 100MB+) to your site and staging without error. Was it a particular image / file size that was failing?

**Closed** 2019-07-19 11:28 UTC
Labels: bug, needs-info
