### ISSUE TITLE
names of newly entered varieties no longer displayed in editing mode

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6156] opened 2020-02-25 14:07 UTC
- Added by [Jens G. Rohwer](http://lauraceae.myspecies.info/user/2)
- Scratchpad: [Lauraceae](http://lauraceae.myspecies.info)

### Description:

I just added Neolitsea cassia var. rigescens 
Chakrabarty, Phytotaxa 419: 209. 2019.
In "Lauraceae Taxonomy" the newly added name is displayed correctly in the search mode, but not in the editing mode (http://lauraceae.myspecies.info/taxonomy/term/18657#overlay=admin/structure/taxonomy/lauraceae_taxonomy//18657%3Fdestination%3Dtaxonomy/term/18657), where it is displayed as "Neolitsea cassia" only.  Previously added variety names are still displayed correctly, with "var. ..."

**Comment by jrdh** [comment] 2020-02-25 14:39
Pretty sure this is a dupe of https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6152.

**Closed by jrdh** 2020-02-25 14:39 UTC
