### ISSUE TITLE
Cannot enter into edit mode-Lice

### ISSUE THREAD

**Issue by Phthiraptera** [NaturalHistoryMuseum/scratchpads2#6556] opened 2022-06-06 14:43 UTC
Hi,

Previously when I click edit, a transparent blank black page will appear onto of the webpage I was working and the status will record connecting xxxx then after a little while I will enter into the edit mode/page. But since last Wednesday, it stop short of the blank black page and status keep saying connecting.

connecting to prod.ap.batic.cudasvc.com

Can you help as I cannot work at all. 

Cheers
Sam (lice volunteer)

**Comment by Phthiraptera** [comment] 2022-06-06 14:58
Hi,

First time using this Github and not sure what I am supposed to do as I am not very familiar with IT jargon etc etc. The page that I was working seems to load now after 1 hr.  so I will see whether it will continue to work. if not I will try posting another issue and this time not click the close button.

Thanks

________________________________

**Comment by Phthiraptera** [comment] 2022-06-06 15:52
Hi 

Since I change my browser to Chrome, it seems to be working much faster. May be it has something to do with Firefox recently tightening their security.

**Comment by therobyouknow** [comment] 2022-06-06 16:55
Thank you @Phthiraptera for advising me of this issue and on email.

I can confirm I also see this issue with Firefox and see it load faster with Chrome.

For example, with the URL: https://phthiraptera.myspecies.info/#overlay=admin/content

![image](https://user-images.githubusercontent.com/1080646/172204113-62e178d3-212c-42ec-9c3a-b3b66c187552.png)

Thank you for advising me that it is quicker on Chrome.  If you are happy using Chrome then that can be a temporary solution while I work out why Firefox is slower.

This problem appears to be related to the overlay - this is the page that is overlaid on top of something else when you click on a link.  

The overlay can be switched off if it isn't useful to you. I would recommend this because myself I can't see much benefit of it. It can be switched back on if needed but I think this page delay problem will still be seen when it is on.

Non-overlay versions of pages can be used instead too, whether the overlay is switched on or off.

So for example, a page which uses the overlay is: https://phthiraptera.myspecies.info/#overlay=admin/content

The same page which doesn't use the overlay is: https://phthiraptera.myspecies.info/admin/content

Note how the `#overlay=` is absent from the non-overlay version.  

So if you have a page that's taking long to load, you can see if it has `#overlay=` in its web address/url and you can remove it from the address in your web-browser's url address box and click reload.

If we switch off overlay then all pages won't have the overlay.

Would you like me to switch off the overlay on your site?

**Technical analysis so far.**
Technically I think the problem is that the overlay itself is contacting `prod.ap.batic.cudasvc.com` which is a different address from your phthiraptera.myspecies.info website  Because it is different, the web browser's security can think there is a problem, so you see the page not loading. I might want to investigate why `prod.ap.batic.cudasvc.com` is being used to try to solve the problem.

A simpler approach might be to just turn off overlay.

**Comment by Phthiraptera** [comment] 2022-06-06 16:59
Hi

Working with Chrome right now but prefer Firefox if possible. So will wait and meanwhile will use Chrome for the project work.

Thanks for looking into it and also may work out how to work n Firefox.

Cheers
Sam
________________________________

**Comment by poospiza** [comment] 2022-06-07 06:56
This morning using Firefox I am not experiencing the slow loading of pages (Content) that happened yesterday. 
Thanks both or looking into this issue.
Nicholas

**Comment by Archilegt** [comment] 2022-06-07 15:13
@therobyouknow, this seems a non-Scratchpad issue, most likely caused by the NHM Barracuda Web Application Firewall settings. An outbound connection from the Barracuda WAF to prod.ap.batic.cudasvc.com (port 443) is required for proper operation.
Myriatrix has also slowed down.

**Comment by Phthiraptera** [comment] 2022-06-07 15:24
Hi, 

This morning after reading about Firefox being Ok, I started using it and it was fine for an hour and then it started to slow down. So I decided to use Chrome instead.

I still prefer to use Firefox but have not tried your advice of removing the #overlay= from the URl and reloading it. May Try that next time. 

A question is would removing the overlay reduces the security of the website? If it does not reduces security or alters anything (important), I am quite happy to work without the overlay. But reading what Archilegt's comment, it may not be take simple.

What I found working with Chrome is that when I open a file from my explorer, it appears as a webpage which occupies another tab and takes up room along my browser bar. I am working on a small tablet so it squeezes everything. While working on the Firefox, if it is opens separately, which I am used to..

Cheers
Sam

**Comment by Phthiraptera** [comment] 2022-06-16 14:26
Hi 

Just to let everyone knows that Firefox browser is working fine with the Phthiraptera website. Thought I work for a few days with it first before reporting. Seems fine for the whole week. Thanks Rob for looking into it.

Cheers
Sam

**Comment by therobyouknow** [comment] 2022-07-08 09:54
Thank you @Phthiraptera closing ticket.

**Closed by therobyouknow** 2022-07-08 09:54 UTC
