### ISSUE TITLE
File creation/upload date reset each day

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5711] opened 2018-12-05 16:47 UTC
Spoken to @benscott about this on Slack before, still occurring. It's a problem as in various places media are sorted by this details.

**Comment by jrdh** [comment] 2018-12-05 16:57
Duplicate of: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5700

**Closed by jrdh** 2018-12-05 16:57 UTC
Labels: bug
