### ISSUE TITLE
Italics in Biblio Titles

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5872] opened 2019-03-06 12:46 UTC
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

I have been trying to put `<i> </i>` around species names in literature titles.

It won't save because it says invalid html code.

Thanks

**Comment by benscott** [comment] 2019-03-07 09:42
I think this might be caused by this update (validating correct html in literature titles):

https://github.com/NaturalHistoryMuseum/scratchpads2/pull/5854/commits/0e2133e920b83c161603d0716fe4cdcd217e1617

**Comment by gsonet** [comment] 2019-03-27 08:17
I also have troubles with italics in Biblio titles but I do not get how to solve this using the xml tag... If I add <xml> in the title, italic is displayed but then "<xml>" is visible. See here: http://jemu.myspecies.info/node/4669#overlay=node/4669/edit
Thank you for your help!

**Comment by alycejenni** [comment] 2019-04-02 12:41
@gsonet you can't do this manually - adding `xml` tags only works in the backend. They're not added to the actual title. Unfortunately I haven't found a temporary workaround, but this bug should be fixed in the next release.

**Closed** 2019-04-12 12:51 UTC
Labels: bug
