### ISSUE TITLE
Unable to connect to twitter account

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6249] opened 2020-07-21 09:39 UTC
- Added by [Ariane Buckenmeyer](http://acoela.myspecies.info/en/user/32003)
- Scratchpad: [The Stylet ](http://acoela.myspecies.info)

### Description:

Error message: "Could not obtain a valid token from the Twitter API. Please review the configuration" prior to adding an account.

**Comment by jrdh** [comment] 2020-07-21 16:41
This is a duplicate of https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5877

**Closed by jrdh** 2020-07-21 16:41 UTC
